[DNM] Device code
oauthlib/oauthlib pull request #640
Opened 2018-12-28 19:32 UTC by jcampbell05

This is my PR to track my work on #626, once I'm ready for this to be reviewed I'll update this description with details of what I've been working on.

For now I'll discuss development in gitter :)

2019-01-24 20:12 UTC, duaneking commented
This PR will be deleted/closed if the issues are not fixed.

I'm leery of a custom login flow that doesn't cite any RFC;s being added to the lib anyway, since it's a new attack vector.

2019-01-25 09:00 UTC, jcampbell05 commented
> This PR can not be included or merged if the issues are not fixed.
> 

Of course but I'm still working on it locally in a project to test the APIs.

> I'm leery of a custom login flow that doesn't cite any RFC;s being added to the lib anyway, since it's a new attack vector.
> 
> What RFC's does this implement? This seems like a custom flow and as a one-off pr for an unknown process flow with no RFC or standardization, I'm inclined to reject it anyway.
> 

It implements this draft flow https://tools.ietf.org/html/draft-ietf-oauth-device-flow-13

> Edit: I looked at the original link and I'm not sure this is a good fit for the lib until we support JWT's fully for clients.

This flow doesn't require JWT so not sure what the blocker is there.

2019-01-25 19:21 UTC, duaneking commented
Its architectural.

If you look at the token types and the generator it looks like some test shims exist for JWT that point out the problems in the WebApp client, but they are otherwise dead code as thye are only referenced in tests.

For example, grant types etc are currently assumed, so that architectural work will need to be done to support multiple, in order to support both this device stuff and the JWT.

2019-01-29 18:46 UTC, duaneking commented
The change hasn't happened yet, its just something I noticed the other day so I'm thinking we should work to common goals.  The grant_type for example is hard coded but for JTW you need a very different value because an assert needs to happen that the value was used.

We need to be able to support a different type based on the type of token being used; if you want to do that work as part of your PR it would help with support for both.

2019-08-11 14:29 UTC, thedrow commented
FYI we're at [draft 15](https://tools.ietf.org/html/draft-ietf-oauth-device-flow-15) now.
If you still want to work on the PR, you'll have to rebase and update it.

2019-08-12 19:10 UTC, jcampbell05 commented
@thedrow no worries, I will do so.

2019-08-29 08:46 UTC, JonathanHuot commented
Finalized as RFC8628 : https://tools.ietf.org/html/rfc8628

2019-08-29 14:25 UTC, jcampbell05 commented
I'l restart this work with the final RFC :)

2019-10-23 11:23 UTC, thedrow commented
@jcampbell05 Ping?
Any change to get some progression on this PR soon or should we close it for now?

2020-02-28 05:52 UTC, auvipy requested changes
Please rebase and let us know if you got the bandwitdh to move this forward! great job so far!

2020-04-22 10:04 UTC, thedrow commented
@jcampbell05 Is that a no?
Last chance before we close this and open an issue instead.

2020-04-22 16:01 UTC, jcampbell05 commented
No lets close it and open an issue - I've ran out of bandwidth at the moment but this can server as a POC at least for anyone wanting to pick this back up

2020-05-12 16:33 UTC, auvipy commented
> No lets close it and open an issue - I've ran out of bandwidth at the moment but this can serve as a POC at least for anyone wanting to pick this back up
> 
> If I have time in the future then can open a new PR

I will push on your branch. I will take on this :)

2022-07-06 13:16 UTC, auvipy commented
> @auvipy Is this still being actively worked on?

no, need to come back to this, are you interested?

2023-03-24 11:39 UTC, auvipy requested changes

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/__init__.py
> +from __future__ import absolute_import, unicode_literals
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/endpoints/code.py
> +from __future__ import absolute_import, unicode_literals
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/endpoints/verification.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/endpoints/verification.py
> +from __future__ import absolute_import, unicode_literals
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/grant_types/__init__.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/grant_types/__init__.py
> +from __future__ import unicode_literals, absolute_import
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/grant_types/device_code.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/grant_types/device_code.py
> +from __future__ import absolute_import, unicode_literals
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/draft_ietf13/tokens.py
> +from __future__ import absolute_import, unicode_literals
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/rfc6749/endpoints/introspect.py
>  # -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/rfc6749/endpoints/pre_configured.py
>  # -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on oauthlib/oauth2/rfc6749/endpoints/resource.py
>  # -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on tests/oauth2/draft_ietf13/grant_types/test_device_code.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2023-03-24 11:39 UTC, auvipy commented on tests/oauth2/draft_ietf13/grant_types/test_device_code.py
> +from __future__ import absolute_import, unicode_literals
```suggestion
```

2024-10-29 21:44 UTC, brianhelba commented
@jcampbell05 @auvipy Is this obsolete now that #881 is merged, or does this PR provide additional features beyond that?

2024-10-30 09:52 UTC, auvipy commented
I think it is superseded by new ones

2024-10-30 16:38 UTC, jcampbell05 commented
> @jcampbell05 @auvipy Is this obsolete now that #881 is merged, or does this PR provide additional features beyond that?

I'm not familiar with the other PR but I'll close this for now. If anything is needed for the final spec, future implementors can be linked to this.

2024-10-30 16:38 UTC, closed without merging