Allow non-HTTPS issuer when OAUTHLIB_INSECURE_TRANSPORT.
oauthlib/oauthlib pull request #803
Opened 2022-02-04 01:13 UTC by luhn

Use `utils.is_secure_transport` to validate issuer, that way `OAUTHLIB_INSECURE_TRANSPORT` is taken into account.

2022-02-04 04:26 UTC, auvipy requested changes

2022-02-04 04:26 UTC, auvipy commented on oauthlib/oauth2/rfc6749/endpoints/metadata.py
> +            if not is_secure_transport(array[key]):
can you please verify this change with unit test?

2022-02-04 06:46 UTC, luhn commented
I was going off of the existing unit tests for the metadata endpoint, which don't seem to test the validations?  Likely because the validations don't result in a user-facing error but a hard `ValueError`.

Happy to whip up a quick test if you'd still like me to.

2022-02-04 07:58 UTC, auvipy commented
yes please

2022-03-06 17:24 UTC, auvipy approved these changes

2022-03-06 17:24 UTC, merged