Add DeviceCodeGrant type for device code flow(rfc8628) section 3.4 & 5.5
oauthlib/oauthlib pull request #889
Opened 2024-11-16 16:08 UTC by duzumaki

Device grant type to suport [3.4](https://datatracker.ietf.org/doc/html/rfc8628#section-3.4) & [3.5](https://datatracker.ietf.org/doc/html/rfc8628#section-3.5)

----
In case anyone asks about **openid connec**t on top of the device flow code.

I am aware some identity providers like[microsoft](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-device-code#successful-authentication-response), [okta](https://developer.okta.com/docs/guides/device-authorization-grant/main/#request-access-id-and-refresh-tokens), [auth0](https://auth0.com/docs/get-started/authentication-and-authorization-flow/device-authorization-flow/call-your-api-using-the-device-authorization-flow) all return id tokens with their device flows. 

Keep in mind those are off-spec implementations and openid makes no mention of the device flow. To reduce the scope of this pr I opted to not add openID to the device flow here. I may have a follow up pr that implements it depending on my needs but either way a standard on-spec device code flow should be merged and released first

2024-11-17 12:01 UTC, auvipy requested changes
also there are tons of unrelated changes to this PR

2024-11-17 12:01 UTC, auvipy commented on tests/oauth2/rfc8628/grant_types/test_device_code.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2024-11-17 12:10 UTC, duzumaki commented
Which changes? the Ruff one? That was done because in a previous PR we wanted better for string but the ruff default is 255


regarding usage of the errors. It's my understanding of oauthlib that it provides the building blocks needed to build your own auth server. 

In this case, these are errors that are raised when the device is polling the token endpoint, which is where you'll use the error object from oauthlib and raise it there

Where I used it was in a branch in django oauth toolkit and ultimately an auth server I've built

2024-11-17 12:10 UTC, duzumaki commented
@auvipy 

Which changes? the Ruff one? That was done because in a previous PR we wanted better for string but the ruff default is 255


regarding usage of the errors. It's my understanding of oauthlib that it provides the building blocks needed to build your own auth server. 

In this case, these are errors that are raised when the device is polling the token endpoint, which is where you'll use the error object from oauthlib and raise it there

Where I used it was in a branch in django oauth toolkit and ultimately an auth server I've built

2024-11-17 12:14 UTC, auvipy commented
> Where I used it was in a branch in django oauth toolkit and ultimately an auth server I've built. As usage of db models is also involved in determining when these errors are raised (by checking if for example the device flow session is expired).

some examples would be nice

2024-11-18 12:48 UTC, duzumaki commented
@auvipy added a [pseudocode implementation](https://github.com/oauthlib/oauthlib/pull/889/commits/75c42f395eee37055fb76e35cfb5a4f4a2852e02). 


Do let me know if anything doesn't make sense or may need a change

2024-11-25 21:53 UTC, duzumaki commented
@thedrow I think Asif is on parental leave. Is this a pr you could review please?

2024-12-04 10:03 UTC, duzumaki commented on oauthlib/oauth2/rfc8628/__init__.py
> +from oauthlib.oauth2.rfc8628.errors import (
https://github.com/oauthlib/oauthlib/commit/f5f6f90585e988883d6201e3d69420a597a1b277

2024-12-04 10:03 UTC, duzumaki commented on oauthlib/oauth2/rfc8628/errors.py
> +class AuthorizationPendingError(OAuth2Error):
https://github.com/oauthlib/oauthlib/commit/f5f6f90585e988883d6201e3d69420a597a1b277

2024-12-07 15:50 UTC, auvipy commented on tests/oauth2/rfc8628/grant_types/test_device_code.py
> +# -*- coding: utf-8 -*-
```suggestion
```

2024-12-07 15:51 UTC, auvipy approved these changes

2024-12-08 07:28 UTC, merged